# Generated by Django 5.2.4 on 2025-08-11 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_gender'),
        ('locations', '0003_alter_city_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bank_iban',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='passport',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='host_user', to='locations.address'),
        ),
    ]
