# Generated by Django 5.2.4 on 2025-08-13 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_bank_iban_user_passport_user_user_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_address',
        ),
    ]
