# Generated by Django 5.2.4 on 2025-08-06 20:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Amenities')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('cost', models.DecimalField(db_index=True, decimal_places=2, max_digits=10, verbose_name='Price')),
                ('rental_type', models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly')], max_length=25)),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('studio', 'Studio'), ('house', 'House'), ('townhouse', 'Townhouse'), ('room', 'Room'), ('loft', 'Loft'), ('duplex', 'Duplex'), ('penthouse', 'Penthouse'), ('bungalow', 'Bungalow'), ('cottage', 'Cottage'), ('office', 'Office'), ('retail', 'Retail space'), ('warehouse', 'Warehouse'), ('other', 'Other')], db_index=True, max_length=25, verbose_name='Property type')),
                ('square_meters', models.DecimalField(db_index=True, decimal_places=2, max_digits=5)),
                ('bedrooms', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Bedrooms')),
                ('bathrooms', models.IntegerField(blank=True, null=True, verbose_name='Bathrooms')),
                ('max_guests', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Guests')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('available', models.BooleanField(default=True, verbose_name='Available')),
                ('reviews_count', models.PositiveIntegerField(default=0, verbose_name='Amount of reviews')),
                ('average_rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='Average rating of the property')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amenities', models.ManyToManyField(related_name='properties', to='properties.amenities', verbose_name='Amenities of the property')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
        ),
    ]
