# Generated by Django 5.2.4 on 2025-08-07 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-created_at'], 'permissions': (), 'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
    ]
