# Generated by Django 5.2.4 on 2025-08-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_property_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='max_guests',
            field=models.IntegerField(db_index=True, verbose_name='Guests'),
        ),
    ]
