# Generated by Django 5.2.4 on 2025-08-10 16:13

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_property_max_guests'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='property',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='property',
            old_name='bedrooms',
            new_name='rooms',
        ),
        migrations.AddField(
            model_name='property',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
