# Generated by Django 5.2.4 on 2025-08-11 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_property_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='available',
        ),
    ]
