# Generated by Django 5.2.4 on 2025-08-13 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_city_unique_together'),
        ('properties', '0006_remove_property_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='locations.address'),
            preserve_default=False,
        ),
    ]
