# Generated by Django 5.2.4 on 2025-08-10 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Country Name')),
                ('iso2', models.CharField(db_index=True, max_length=2, unique=True, verbose_name='Two-letter country codes as per ISO 3166-1 alpha-2.')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='Zip Code')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='City Name')),
                ('latitude', models.FloatField(verbose_name='latitude')),
                ('longitude', models.FloatField(verbose_name='longitude')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.country', verbose_name='Country')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'ordering': ['country', 'name'],
                'unique_together': {('name', 'country')},
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(db_index=True, max_length=255, verbose_name='Street')),
                ('house_number', models.CharField(max_length=255, verbose_name='House number')),
                ('apartment_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Apartment/block number')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='locations.city', verbose_name='City')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'ordering': ['city__country__name', 'city__name', 'street', 'house_number', 'apartment_number'],
                'unique_together': {('city', 'street', 'house_number', 'apartment_number')},
            },
        ),
    ]
