# Generated by Django 5.2.4 on 2025-08-10 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_city_zip_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name', 'country', 'zip_code')},
        ),
    ]
