# Generated by Django 5.2.4 on 2025-08-12 13:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_booked_property_alter_booking_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='total_price',
        ),
        migrations.AddField(
            model_name='booking',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='city_taxes',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Lodging tax'),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price_brutto',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Total price'),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price_netto',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Total price'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='amount_of_guests',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)], verbose_name='Amount of guests'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_date',
            field=models.DateField(verbose_name='Check-out'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_date',
            field=models.DateField(verbose_name='Check-in'),
        ),
    ]
