# Generated by Django 5.2.4 on 2025-08-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_remove_booking_total_price_booking_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='total_price_brutto',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Total price taxes incl.'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price_netto',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Price for your stay'),
        ),
    ]
