# Generated by Django 5.2.4 on 2025-08-06 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='properties.property', verbose_name='Value for money')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='ID of the reviewer')),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='Overall rating of the property')),
                ('cleanliness', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='Cleanliness')),
                ('comfort_and_facilities', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='Comfort and facilities')),
                ('staff_communication', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='Communication with staff')),
                ('localisation', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='Localisation')),
                ('value_for_money', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='Value for money')),
                ('wifi_connection', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='Quality of Wi-Fi connection')),
                ('review_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='reviews.review', verbose_name='Ratings')),
            ],
        ),
    ]
