# Generated by Django 5.2.4 on 2025-08-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='property',
            new_name='property_id',
        ),
        migrations.AddField(
            model_name='review',
            name='average_rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='Overall rating of the property'),
        ),
        migrations.AddField(
            model_name='review',
            name='cleanliness',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='Cleanliness'),
        ),
        migrations.AddField(
            model_name='review',
            name='comfort_and_facilities',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='Comfort and facilities'),
        ),
        migrations.AddField(
            model_name='review',
            name='localisation',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='Localisation'),
        ),
        migrations.AddField(
            model_name='review',
            name='staff_communication',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='Communication with staff'),
        ),
        migrations.AddField(
            model_name='review',
            name='value_for_money',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='Value for money'),
        ),
        migrations.AddField(
            model_name='review',
            name='wifi_connection',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='Quality of Wi-Fi connection'),
        ),
        migrations.DeleteModel(
            name='Ratings',
        ),
    ]
