# Generated by Django 5.2.4 on 2025-08-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_review_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='cleanliness',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=3, verbose_name='Cleanliness'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comfort_and_facilities',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=3, verbose_name='Comfort and facilities'),
        ),
        migrations.AlterField(
            model_name='review',
            name='localisation',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=3, verbose_name='Localisation'),
        ),
        migrations.AlterField(
            model_name='review',
            name='staff_communication',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=3, verbose_name='Communication with staff'),
        ),
        migrations.AlterField(
            model_name='review',
            name='wifi_connection',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=3, verbose_name='Quality of Wi-Fi connection'),
        ),
    ]
